library(eeguana)

test_that("defunct functions", {
  expect_error(downsample())
  expect_error(segment())
  expect_error(interpolate_tbl())
  expect_error(event_to_ch_NA())
  expect_error(eeg_intervals_to_NA())
  expect_error(ch_filt_low_pass())
  expect_error(ch_filt_high_pass())
  expect_error(ch_filt_band_pass())
  expect_error(ch_filt_stop_pass())
  expect_error(events())
  expect_error(`events<-`())
  expect_error(summarize_all_ch())
  expect_error(summarize_at_ch())
  expect_error(plot_gg())
  expect_error(ch_baseline())
})
